//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMetadata
    {
        public string docID { get; set; }
        public string docName { get; set; }
        public string dateOfCreation { get; set; }
        public string patientID { get; set; }
        public string userID { get; set; }
    
        public virtual DocumentStorage DocumentStorage { get; set; }
        public virtual iCAREUser iCAREUser { get; set; }
        public virtual PatientRecord PatientRecord { get; set; }
    }
}
