
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Group13_iCAREAPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class iCAREUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public iCAREUser()
    {

        this.DocumentMetadata = new HashSet<DocumentMetadata>();

        this.TreatmentRecord = new HashSet<TreatmentRecord>();

        this.WorkerGeoCode = new HashSet<WorkerGeoCode>();

        this.UserRole = new HashSet<UserRole>();

    }


    public string ID { get; set; }

    public string name { get; set; }

    public string profession { get; set; }

    public string adminEmail { get; set; }

    public Nullable<System.DateTime> dateHired { get; set; }

    public Nullable<System.DateTime> dateFinished { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DocumentMetadata> DocumentMetadata { get; set; }

    public virtual iCAREUser iCAREUser1 { get; set; }

    public virtual iCAREUser iCAREUser2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TreatmentRecord> TreatmentRecord { get; set; }

    public virtual UserPassword UserPassword { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkerGeoCode> WorkerGeoCode { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserRole> UserRole { get; set; }

}

}
