//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModificationHistory
    {
        public string docID { get; set; }
        public System.DateTime dateOfModification { get; set; }
        public string descrption { get; set; }
        public string modificationNum { get; set; }
    
        public virtual DocumentMetadata DocumentMetadata { get; set; }
    }
}
