
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Group13_iCAREAPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserPassword
{

    public string ID { get; set; }

    public string userName { get; set; }

    public string encryptedPassword { get; set; }

    public int passwordExpiryTime { get; set; }

    public System.DateTime userAccountExpiryDate { get; set; }



    public virtual iCAREUser iCAREUser { get; set; }

}

}
